spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conecta21?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
api:
  security:
    token:
      secret: ${JWT_SECRET:minha_senha_secreta_super_segura_123}